### ISSUE TITLE
citing a blog post, is it okay or should I appear like I came up with softF1?

### ISSUE THREAD

**Issue by gabriben** [gabriben/multilabel#3]
https://github.com/gabriben/multilabel/blob/cc7b4f15b317ba03029ae4f311ab5d324da553e8/sections/04-method.tex#L55

**Comment by gabriben** [comment]
the blog post
https://towardsdatascience.com/the-unknown-benefits-of-using-a-soft-f1-loss-in-classification-systems-753902c0105d

**Comment by dodijk** [comment]
I do not think claiming softF1 is the solution. I think we should establish that there is already a history of custom loss functions to solve particular challenges. We can reference soft F1 as a practitioners attempt to directly optimize for F1, either by citing the blogpost or referencing it in a footnote.
